#spring:
#  datasource:
#    dynamic:
#      primary: master
#      datasource:
#        master:
#          username: wxy
#          password: wxy
#          url: jdbc:mysql://101.43.76.117:3307/zjh?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
#  redis:
#    database: 1
#    host: 101.43.76.117
#    password: redis
#    port: 6379